//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.SolutionOwner.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RI.SolutionOwner.WebAPI.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Parameter deactivated successfully..
        /// </summary>
        internal static string msdPOSParameterDeactivated {
            get {
                return ResourceManager.GetString("msdPOSParameterDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category created successfully..
        /// </summary>
        internal static string msgCategoryCreation {
            get {
                return ResourceManager.GetString("msgCategoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted successfully..
        /// </summary>
        internal static string msgCategoryDeleteSuccess {
            get {
                return ResourceManager.GetString("msgCategoryDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category in use..
        /// </summary>
        internal static string msgCategoryDeleteWarning {
            get {
                return ResourceManager.GetString("msgCategoryDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exists..
        /// </summary>
        internal static string msgCategoryDuplicate {
            get {
                return ResourceManager.GetString("msgCategoryDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated successfully..
        /// </summary>
        internal static string msgCategoryupdation {
            get {
                return ResourceManager.GetString("msgCategoryupdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleted successfully..
        /// </summary>
        internal static string msgDeleteSuccess {
            get {
                return ResourceManager.GetString("msgDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete the process..
        /// </summary>
        internal static string msgExpectationFailed {
            get {
                return ResourceManager.GetString("msgExpectationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature activated successfully..
        /// </summary>
        internal static string msgFeatureActivate {
            get {
                return ResourceManager.GetString("msgFeatureActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature created successfully..
        /// </summary>
        internal static string msgFeatureCreation {
            get {
                return ResourceManager.GetString("msgFeatureCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature deactivated successfully..
        /// </summary>
        internal static string msgFeatureDeActivate {
            get {
                return ResourceManager.GetString("msgFeatureDeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Feature in use..
        /// </summary>
        internal static string msgFeatureDeleteWarning {
            get {
                return ResourceManager.GetString("msgFeatureDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature deleted successfully..
        /// </summary>
        internal static string msgFeatureDeletion {
            get {
                return ResourceManager.GetString("msgFeatureDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature name or Link already exists..
        /// </summary>
        internal static string msgFeatureDuplicate {
            get {
                return ResourceManager.GetString("msgFeatureDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature updated successfully..
        /// </summary>
        internal static string msgFeatureUpdation {
            get {
                return ResourceManager.GetString("msgFeatureUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found..
        /// </summary>
        internal static string msgNoRecord {
            get {
                return ResourceManager.GetString("msgNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Parameter activated successfully..
        /// </summary>
        internal static string msgPOSParameterActivated {
            get {
                return ResourceManager.GetString("msgPOSParameterActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS parameter created successfully..
        /// </summary>
        internal static string msgPOSParameterCreated {
            get {
                return ResourceManager.GetString("msgPOSParameterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS parameter deleted successfully..
        /// </summary>
        internal static string msgPOSParameterDeleted {
            get {
                return ResourceManager.GetString("msgPOSParameterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS parameter name already exists, please try another name..
        /// </summary>
        internal static string msgPOSParameterDuplicate {
            get {
                return ResourceManager.GetString("msgPOSParameterDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS parameter updated successfully..
        /// </summary>
        internal static string msgPOSParameterUpdated {
            get {
                return ResourceManager.GetString("msgPOSParameterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role activated successfully..
        /// </summary>
        internal static string msgRoleActivation {
            get {
                return ResourceManager.GetString("msgRoleActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully..
        /// </summary>
        internal static string msgRoleCreation {
            get {
                return ResourceManager.GetString("msgRoleCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deactivated successfully..
        /// </summary>
        internal static string msgRoleDeActivation {
            get {
                return ResourceManager.GetString("msgRoleDeActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be deleted as users are mapped to this role..
        /// </summary>
        internal static string msgRoleDeleteWarning {
            get {
                return ResourceManager.GetString("msgRoleDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name already exists, please try another role name..
        /// </summary>
        internal static string msgRoleDuplicate {
            get {
                return ResourceManager.GetString("msgRoleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role updated successfully..
        /// </summary>
        internal static string msgRoleUpdation {
            get {
                return ResourceManager.GetString("msgRoleUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activated successfully..
        /// </summary>
        internal static string msgUserActivate {
            get {
                return ResourceManager.GetString("msgUserActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        internal static string msgUserCreation {
            get {
                return ResourceManager.GetString("msgUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deactivated successfully..
        /// </summary>
        internal static string msgUserDeActivate {
            get {
                return ResourceManager.GetString("msgUserDeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        internal static string msgUserDeleteSuccess {
            get {
                return ResourceManager.GetString("msgUserDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user already exist with the emailid, please try another emailid..
        /// </summary>
        internal static string msgUserDuplication {
            get {
                return ResourceManager.GetString("msgUserDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        internal static string msgUserUpdation {
            get {
                return ResourceManager.GetString("msgUserUpdation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Error: Please report this problem or try again later..
        /// </summary>
        internal static string msgWebServiceError {
            get {
                return ResourceManager.GetString("msgWebServiceError", resourceCulture);
            }
        }
    }
}
